### ISSUE TITLE
Après déconnexion personnage revien en Skin PNJ et non état de la création

### ISSUE THREAD

**Issue by Salto4501** [esx-framework/esx_skin#55]
Je crée mon personnage il s'enregistre en BDD. Je me deconnecte et reconnecte et je revien en pnj mais bien a la position que j'ai quitter ! C'est juste mon personnage qui ne veux pas apparaitre mais le reste et la

**Comment by BTNGaming** [comment]
Same issue here. I create a character fully. But when I relog or reboot the server, I spawn in as a random black pen. Only scripts I have installed are es-entended and the required basics such as esx skin, skin changer, esx menus

**Comment by ThomasGames317** [comment]
-----------------------------Français---------------------------------------
Bonjour, j'ai trouvez une solution à ce problème.

Ouvrir le fichier main.lua se trouvant dans server-data/resources/[esx]/esx_skin/client
Puis ajouter ceci après la première fonction (environ ligne 11)

`RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded', function(playerData)
    ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin)
        TriggerEvent('skinchanger:loadSkin', skin)
    end)
end)`

Cela permettras de charger le skin de votre personnage lors de la connexion au serveur en attendent un patch. 

Bonne journée.
Garrys


--------------------------------English-----------------------------------
Hello, I have found a solution to this problem.

Open the main.lua file located in server-data / resources / [esx] / esx_skin / client
Then add this after the first function (about line 11)

`RegisterNetEvent ('esx: playerLoaded')
AddEventHandler ('esx: playerLoaded', function (playerData)
    ESX.TriggerServerCallback ('esx_skin: getPlayerSkin', function (skin)
        TriggerEvent ('skinchanger: loadSkin', skin)
    end)
end) `

This will load your character's skin when connecting to the server while awaiting a patch.

Have a good day.
Garrys

**Comment by battlezoneyt** [comment]
having the same issue. every time when people exit and enter they been spawn with different sets of characters and skin mean gone mad, like in shops when i try to change shits its changing something else. please fix it ASAP.

**Comment by BTNGaming** [comment]
I just created a pull request that fixes this issue.

https://github.com/esx-framework/esx_skin/pull/72

Most people don't check the code, to realize that part of the LOAD CHARACTER SKIN is disabled.
