### ISSUE TITLE
Create char but reload as ped on relog/revive

### ISSUE THREAD

**Issue by BTNGaming** [esx-framework/esx_skin#56]
I create a character fully. But when I relog or reboot the server, I spawn in as a random black pen. Only scripts I have installed are es-entended and the required basics such as esx skin, skin changer, esx menus.

NO Errors to be found anywhere.

**Comment by CroLuka** [comment]
Same problem here.

**Comment by umutc4n** [comment]
Same problem here.

**Comment by kango76** [comment]
Same problem here.

**Comment by Mol3kule** [comment]
Same issue here

**Comment by Fhercho89** [comment]
Same here and nobody answers..

**Comment by ayemarc** [comment]
the way i got mine to work was having esx_ambulance resource installed and by removing mapmanager and spawnmanager from my server.cfg, idk if it'll work for you guys

**Comment by BTNGaming** [comment]
I just created a pull request that fixes this issue.

https://github.com/esx-framework/esx_skin/pull/72

Most people don't check the code, to realize that part of the LOAD CHARACTER SKIN is disabled.
