### ISSUE TITLE
Loading wrong Character and Loading wrong menu skins in shops(Dress shop, Hair Shop)

### ISSUE THREAD

**Issue by battlezoneyt** [esx-framework/esx_skin#62]
Every time when people exit and enter they been spawn with different sets of characters and skin. In shops when i try to change shirts its changing something else. please fix it ASAP.

**Comment by BTNGaming** [comment]
I just created a pull request that fixes this issue.

https://github.com/esx-framework/esx_skin/pull/72

Most people don't check the code, to realize that part of the LOAD CHARACTER SKIN is disabled.
