### ISSUE TITLE
Created character buy spawn as default ped after Login / server restart

### ISSUE THREAD

**Issue by Fhercho89** [esx-framework/esx_skin#63]
Pls help everytime someone relogs it spawns with this skin 
![Screenshot_1](https://user-images.githubusercontent.com/35504359/83180045-397cc300-a0f9-11ea-9b58-84f04d39eee8.png)

**Comment by amo0725** [comment]
ME TOO

**Comment by ScoRp1oNPT** [comment]
Ye me too someone can help?

**Comment by estebantgc10** [comment]
@ScoRp1oNPT @amo0725 @Fhercho89 i was having the same problem and I fix it

**Comment by THEMARCE** [comment]
@estebantgc10 
hello could you tell me how you solved it please

**Comment by imartinezgregori** [comment]
@estebantgc10 how you solved??

**Comment by DavidFdes** [comment]
Did anyone solved this already ? Using ESX 1.2 here

**Comment by BTNGaming** [comment]
I just created a pull request that fixes this issue.

https://github.com/esx-framework/esx_skin/pull/72

Most people don't check the code, to realize that part of the LOAD CHARACTER SKIN is disabled.
