### ISSUE TITLE
Charge with default skin.

### ISSUE THREAD

**Issue by Andreeiii11** [esx-framework/esx_skin#65]
Hello, when i enter to my server i appear with the default skin.

And i have esx_skin skinchanger and esx_clotheshop.
If you need some code line tell me.
I don’t have any error in F8 and console.

Note: When i go to my job and i select Civilian Wear it gives my skin:
image

**Comment by tomasfiguera** [comment]
i have the same problem, some solution here?

**Comment by Danny9865** [comment]
they changed it and it broke... shock

**Comment by deviljin112** [comment]
> they changed it and it broke... shock

ESX 2 does not use this script! It uses modules. None of the scripts are compatible with 2.0.
If you want to continue using these scripts, use 1.final or EXM.

**Comment by MonoChirito** [comment]
it doesnt work for v1 final for me. gives a error index a nil value local xPlayer, but in other scripts the exact GetPlayer from id thing works... i tried so many things and it still doesnt work

**Comment by BTNGaming** [comment]
I just created a pull request that fixes this issue.

https://github.com/esx-framework/esx_skin/pull/72

Most people don't check the code, to realize that part of the LOAD CHARACTER SKIN is disabled.
