### ISSUE TITLE
Error ESX_SKIN attempt to index a nil value (local 'xPlayer')

### ISSUE THREAD

**Issue by Dukelegends** [esx-framework/esx_skin#78]
https://images-ext-2.discordapp.net/external/Zzl66PxzeR4y03Fkk7jpTSro70V5nXdvhE4jMWotUd4/https/image.prntscr.com/image/Qn0GNXFhRjOTXEhYAJwh_Q.png

**Comment by Dislaik** [comment]
We are not diviners
