### ISSUE TITLE
ESX_Skin error

### ISSUE THREAD

**Issue by SeptJack** [esx-framework/esx_skin#94]
I get an error when I try to start my server, I can get into my server but when I join my server I get the black screen that says loading then I spawn in and it still says loading and I cant move or anything, all I can do is get into the f8 command screen
![esx_skin error](https://user-images.githubusercontent.com/34425472/105410238-87ff4480-5c29-11eb-9fa0-1c09b895e9c4.png)

**Comment by AviaHumble** [comment]
I'm getting this exact same issue, have you managed to fix it?
